# Generated by Django 2.1 on 2018-08-16 22:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0003_auto_20180816_2249'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='remindertime',
            name='id',
        ),
        migrations.AlterField(
            model_name='remindertime',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL),
        ),
    ]
