# Generated by Django 2.1 on 2018-08-16 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0004_auto_20180816_2257'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='warning_event',
            field=models.IntegerField(choices=[(1, 'Always'), (2, 'Raining tomorrow'), (3, 'Snowing tomorrow'), (4, 'Temperature dropping by 3F tomorrow'), (5, 'Temperature rising by 3F tomorrow')], default=1),
        ),
        migrations.AlterField(
            model_name='remindertime',
            name='reminder_time',
            field=models.IntegerField(choices=[(1, '9:00 pm PST'), (2, '6:00 am PST')], default=1),
        ),
    ]
