# Generated by Django 2.1 on 2018-08-17 00:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0005_auto_20180816_2321'),
    ]

    operations = [
        migrations.AlterField(
            model_name='remindertime',
            name='reminder_time',
            field=models.IntegerField(choices=[(1, '9:00 pm PST every night'), (2, '6:00 am PST every morning')], default=1),
        ),
    ]
