# Generated by Django 2.1 on 2018-08-25 16:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0006_auto_20180817_0039'),
    ]

    operations = [
        migrations.CreateModel(
            name='Weather',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zipcode', models.CharField(max_length=30)),
                ('time', models.DateField(blank=True, default=datetime.datetime(1, 1, 1, 0, 0))),
                ('description', models.CharField(max_length=50)),
                ('weather_sign', models.IntegerField(default=0)),
                ('city', models.CharField(max_length=30)),
                ('temp_min', models.CharField(max_length=10)),
                ('temp_max', models.CharField(max_length=10)),
            ],
        ),
        migrations.AlterField(
            model_name='remindertime',
            name='reminder_time',
            field=models.IntegerField(choices=[(1, '10:00 pm CDT every night'), (2, '6:00 am CDT every morning')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='weather',
            unique_together={('zipcode', 'time')},
        ),
    ]
