# Generated by Django 2.1 on 2018-08-25 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reminder', '0007_auto_20180825_1147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reminder',
            name='warning_event',
            field=models.IntegerField(choices=[(1, 'Always'), (2, 'Raining tomorrow'), (3, 'Snowing tomorrow'), (4, 'Temperature dropping by 10F tomorrow'), (5, 'Temperature rising by 10F tomorrow')], default=1),
        ),
    ]
